### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by jburel**
Small adjustments. 
cc @will-moore

### CODE REVIEW

**Comment by will-moore** [comment]
Looks good, thanks

**Comment by sbesson** [comment]
Lots of flake8 issues in https://github.com/IDR/idr-gallery/runs/5647553424?check_suite_focus=true as well. Is it worth fixing those and/or including the changes in this PR in a release of the app before deploying to IDR? Or is it fine to happen as a follow-up?

**Comment by jburel** [comment]
We can fix the flake8 in a follow-up PR.

**Comment by jburel** [comment]
nothing to be released before deploying

**Comment by will-moore** [comment]
LGTM 👍  - thx

**Pull request merged**
